import type { Metadata } from "next";
import "./globals.css";
import Dashboard from "./dashboard/page";
import DashboardWrapper from "./dashboard/dashboardWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        {/* You can place additional <meta> tags or <link> tags here */}
      </head>
      <body>
       <DashboardWrapper>{children}</DashboardWrapper>
      </body>
    </html>
  );
}
// everything that is continous (in all pages) goes here