import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        {/* You can place additional <meta> tags or <link> tags here */}
      </head>
      <body>
        {/* Global providers or navigation could go here */}
        {children}
      </body>
    </html>
  );
}
